apiVersion: v1
kind: Service
metadata:
  namespace: ns-simplebankapp
  name: simplebankapp-service
  labels:
    app: simplebankapp
spec:
  selector:
    app: simplebankapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30024
  type: NodePort
